### Get all persons
GET http://localhost:3001/api/persons/

### Get person with given ID 
GET http://localhost:3001/api/persons/6898d2c9f42267dc3f300f0a

### Get non existent person
GET http://localhost:3001/api/persons/100

### Delete an entry of the phonebook with given ID
DELETE http://localhost:3001/api/persons/

### Create new person, valid
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
	"name": "Alessandra Percoco",
	"number": "424-1073438"
}

### Create new person, invalid
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
	"name": "Rodrigo",
	"number": "12-092564"
}

### Get info
GET http://localhost:3001/info/

### Modify person
PUT http://localhost:3001/api/persons/6898fae446b5a8627a282623
Content-Type: application/json

{
	"name": "Aa",
	"number": "424-5557738"
}
